### ISSUE TITLE
¿Posible virus?

### ISSUE THREAD

**Issue by vivayoes** [hoksilato2/Cortana-2-Ana#3]
Hola.

Muchas gracias por tu aporte.

He probado a escanear el último archivo que ha subido "Cortana-2-Ana-04b" a Virustotal.com y detecta que tiene un virus. ¿Puede ser un falso positivo?

Un saludo
![Captura de pantalla (4)](https://user-images.githubusercontent.com/62836533/83974787-2be0ed80-a8f0-11ea-90c7-c5faf9e1fbbf.png)

**Comment by hoksilato2** [comment]
¡Vaya! Pues tiene que ser un falso positivo porque el ejecutable no deja de ser un auto-ejecutable creado con 7z. Si quieres, puedes instalarte el 7z y con clic derecho abrir el exe para ver su contenido como si fuera un zip. Verás que está todo el contenido de aquí. 

Se han puesto muy duros con los exe no firmados. El mío, como es lógico, no está firmado y por ejemplo con el nuevo Edge tb dice que ojo con el archivo a descargar. Ahora hay que aceptar mil cosas antes de poder descargarlo.

En resumen: el único ejecutable que hay es el archivo 7z con los scripts dentro. Si quieres, descomprime el exe en una carpeta y escanealo todo con tu antivirus para estar más tranquilo.

**Comment by vivayoes** [comment]
Si, he estado investigando y son falsos positivos.
https://www.2-spyware.com/remove-malicious-moderate-ml-score.html

Gracias de todas formas por contestar. Un saludo
